apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk
  namespace: upexcisedev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helpdesk
  template:
    metadata:
      labels:
        app: helpdesk
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 4.2.2.2
      imagePullSecrets:
      - name: regcred
      containers:
      - name: helpdesk
        image: dockerrepoapi.oasys.co/upexcise/dev/helpdesk:latest       
        ports:
        - containerPort: 3506
        volumeMounts:
        - name: logs-volume
          mountPath:  /DATA/logs/helpdesk
      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: helpdesk-pvc-logs
---
apiVersion: v1
kind: Service
metadata:
  name: helpdesk-svc
  namespace: upexcisedev
spec:
  type: NodePort
  selector:
    app: helpdesk
  ports:
    - port: 3506
      targetPort: 3506
      nodePort: 32015

